# Generated by Django 3.0.2 on 2020-02-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITInstance',
            new_name='Asset',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['hostname'], 'verbose_name': 'asset'},
        ),
    ]
