# Generated by Django 3.0.2 on 2020-02-15 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0002_auto_20200215_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_number',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
