# Generated by Django 3.0.2 on 2020-01-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0002_itinstance_itmodel_rack_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinstance',
            old_name='instance_id',
            new_name='hostname',
        ),
        migrations.RemoveField(
            model_name='itinstance',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='itinstance',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinstance',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rackcity.Rack', verbose_name='related rack'),
        ),
        migrations.AddField(
            model_name='rack',
            name='height',
            field=models.IntegerField(default=42),
        ),
    ]
