# Generated by Django 3.0.2 on 2020-01-26 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0003_auto_20200122_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RenameField(
            model_name='itinstance',
            old_name='height',
            new_name='elevation',
        ),
        migrations.RemoveField(
            model_name='itinstance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itmodel',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='rack_id',
        ),
        migrations.AddField(
            model_name='itinstance',
            name='owner',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinstance',
            name='hostname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='itinstance',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.Rack', verbose_name='related rack'),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_num',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='itmodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'model_number'), name='unique vendor model number'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('row_letter', 'rack_num'), name='unique rack letter and number'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
