# Generated by Django 3.0.2 on 2020-02-15 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rackcity', '0003_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user_id',
        ),
        migrations.AddField(
            model_name='log',
            name='related_assets',
            field=models.ManyToManyField(blank=True, null=True, to='rackcity.Asset', verbose_name='related assets'),
        ),
        migrations.AddField(
            model_name='log',
            name='related_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rackcity.ITModel', verbose_name='related model'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
