# Generated by Django 3.0.2 on 2020-02-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0004_auto_20200215_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='elevation',
            new_name='rack_position',
        ),
    ]
