# Generated by Django 3.0.2 on 2020-01-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0004_auto_20200126_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinstance',
            options={'verbose_name': 'instance'},
        ),
        migrations.AlterModelOptions(
            name='itmodel',
            options={'verbose_name': 'model'},
        ),
        migrations.AlterField(
            model_name='itinstance',
            name='elevation',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='memory_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='num_ethernet_ports',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='num_power_ports',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='height',
            field=models.PositiveIntegerField(default=42),
        ),
    ]
