# Generated by Django 3.0.2 on 2020-01-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0005_auto_20200126_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinstance',
            name='hostname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='itinstance',
            name='owner',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='cpu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='display_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='model_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='storage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='vendor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_num',
            field=models.PositiveIntegerField(),
        ),
    ]
