# Generated by Django 3.0.3 on 2020-02-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0005_auto_20200215_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['datacenter', 'row_letter', 'rack_num', 'is_powered']},
        ),
        migrations.AddField(
            model_name='rack',
            name='is_powered',
            field=models.BooleanField(default=False),
        ),
    ]
