# Generated by Django 3.0.2 on 2020-02-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0005_auto_20200215_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=150)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.Asset', verbose_name='asset')),
                ('network_connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rackcity.NetworkPort')),
            ],
        ),
    ]
