# Generated by Django 3.0.3 on 2020-02-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0006_auto_20200215_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['datacenter', 'row_letter', 'rack_num']},
        ),
    ]
