# Generated by Django 3.0.2 on 2020-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0006_auto_20200126_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['row_letter', 'rack_num']},
        ),
    ]
