# Generated by Django 3.0.2 on 2020-02-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0007_auto_20200215_2042'),
        ('rackcity', '0005_auto_20200215_2100'),
    ]

    operations = [
    ]
