# Generated by Django 3.0.2 on 2020-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0007_auto_20200129_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinstance',
            options={'ordering': ['hostname'], 'verbose_name': 'instance'},
        ),
        migrations.AlterModelOptions(
            name='itmodel',
            options={'ordering': ['vendor', 'model_number'], 'verbose_name': 'model'},
        ),
    ]
