# Generated by Django 3.0.2 on 2020-01-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0008_auto_20200129_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinstance',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
