# Generated by Django 3.0.2 on 2020-02-01 04:33

from django.db import migrations, models
import rackcity.models.it_instance


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0008_auto_20200129_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinstance',
            name='hostname',
            field=models.CharField(max_length=150, unique=True, validators=[rackcity.models.it_instance.validate_hostname]),
        ),
    ]
