# Generated by Django 3.0.2 on 2020-02-16 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0008_auto_20200216_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDUPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_right', models.CharField(choices=[('L', 'L'), ('R', 'R')], max_length=1)),
                ('port_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.CreateModel(
            name='PowerPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='networkport',
            name='unique port names on assets',
        ),
        migrations.AddConstraint(
            model_name='networkport',
            constraint=models.UniqueConstraint(fields=('asset', 'port_name'), name='unique network port names on assets'),
        ),
        migrations.AddField(
            model_name='powerport',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.Asset', verbose_name='asset'),
        ),
        migrations.AddField(
            model_name='powerport',
            name='power_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rackcity.PDUPort'),
        ),
        migrations.AddField(
            model_name='pduport',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.Rack', verbose_name='rack'),
        ),
        migrations.AddConstraint(
            model_name='powerport',
            constraint=models.UniqueConstraint(fields=('asset', 'port_name'), name='unique power port names on assets'),
        ),
        migrations.AddConstraint(
            model_name='pduport',
            constraint=models.UniqueConstraint(fields=('rack', 'left_right', 'port_number'), name='unique port per pdu'),
        ),
    ]
