# Generated by Django 3.0.2 on 2020-02-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0009_auto_20200131_2356'),
        ('rackcity', '0009_auto_20200201_0433'),
    ]

    operations = [
    ]
