# Generated by Django 3.0.2 on 2020-02-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0007_auto_20200215_2042'),
        ('rackcity', '0009_auto_20200216_1939'),
    ]

    operations = [
    ]
