# Generated by Django 3.0.2 on 2020-02-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0010_merge_20200216_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='is_powered',
            new_name='is_network_controlled',
        ),
    ]
