# Generated by Django 3.0.2 on 2020-02-04 02:46

from django.db import migrations, models
import rackcity.models.it_model


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0010_merge_20200203_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='display_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[rackcity.models.it_model.validate_display_color]),
        ),
    ]
