# Generated by Django 3.0.2 on 2020-02-17 14:40

from django.db import migrations
import rackcity.models.fields.rackcity_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0011_auto_20200216_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='itmodel',
            name='num_network_ports',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
