# Generated by Django 3.0.2 on 2020-02-04 17:46

from django.db import migrations, models
import rackcity.models.it_model


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0011_auto_20200204_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='display_color',
            field=models.CharField(default='#394B59', max_length=7, validators=[rackcity.models.it_model.validate_display_color]),
        ),
    ]
