# Generated by Django 3.0.2 on 2020-02-04 18:12

from django.db import migrations, models
import rackcity.models.it_instance


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0011_auto_20200204_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinstance',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[rackcity.models.it_instance.validate_owner]),
        ),
    ]
