# Generated by Django 3.0.2 on 2020-02-17 02:13

from django.db import migrations, models
import rackcity.models.asset


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0011_auto_20200216_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[rackcity.models.asset.validate_hostname]),
        ),
    ]
