# Generated by Django 3.0.2 on 2020-02-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0008_merge_20200217_0437'),
        ('rackcity', '0011_auto_20200216_2056'),
    ]

    operations = [
    ]
