# Generated by Django 3.0.2 on 2020-02-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0012_auto_20200204_1812'),
        ('rackcity', '0012_auto_20200204_1746'),
    ]

    operations = [
    ]
