# Generated by Django 3.0.2 on 2020-02-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0012_auto_20200217_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_number'], 'verbose_name': 'asset'},
        ),
    ]
