# Generated by Django 3.0.2 on 2020-02-04 21:33

from django.db import migrations
import rackcity.models.fields.rackcity_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0012_auto_20200204_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='memory_gb',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
    ]
