# Generated by Django 3.0.2 on 2020-02-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0013_auto_20200217_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkport',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
