# Generated by Django 3.0.2 on 2020-02-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0013_auto_20200204_2133'),
        ('rackcity', '0013_merge_20200204_2154'),
    ]

    operations = [
    ]
