# Generated by Django 3.0.2 on 2020-02-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0012_itmodel_num_network_ports'),
        ('rackcity', '0013_auto_20200217_0543'),
    ]

    operations = [
    ]
