# Generated by Django 3.0.2 on 2020-02-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0014_merge_20200217_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='related_assets',
        ),
        migrations.AddField(
            model_name='log',
            name='related_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackcity.Asset', verbose_name='related asset'),
        ),
    ]
