# Generated by Django 3.0.2 on 2020-02-05 00:12

from django.db import migrations
import rackcity.models.fields.rackcity_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0014_merge_20200205_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='num_ethernet_ports',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='num_power_ports',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
    ]
