# Generated by Django 3.0.2 on 2020-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0015_auto_20200218_0517'),
        ('rackcity', '0014_auto_20200218_0124'),
    ]

    operations = [
    ]
