# Generated by Django 3.0.2 on 2020-02-05 01:16

from django.db import migrations, models
import rackcity.models.rack


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0015_auto_20200205_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='row_letter',
            field=models.CharField(max_length=1, validators=[rackcity.models.rack.validate_row_letter]),
        ),
    ]
