# Generated by Django 3.0.2 on 2020-02-12 06:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0016_auto_20200205_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itmodel',
            name='num_ethernet_ports',
        ),
        migrations.AddField(
            model_name='itmodel',
            name='network_ports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, null=True, size=None),
        ),
    ]
