# Generated by Django 3.0.2 on 2020-02-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0016_merge_20200218_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkport',
            old_name='network_connection',
            new_name='connected_port',
        ),
    ]
