# Generated by Django 3.0.2 on 2020-02-13 02:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0017_auto_20200212_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='network_ports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None),
        ),
    ]
