# Generated by Django 3.0.3 on 2020-02-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0018_auto_20200213_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
