# Generated by Django 3.0.2 on 2020-03-06 05:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rackcity.models.asset


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rackcity', '0018_auto_20200223_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'change planner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_conflict', models.BooleanField(blank=True, default=False)),
                ('asset_number', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('hostname', models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[rackcity.models.asset.validate_hostname])),
                ('rack_position', models.PositiveIntegerField()),
                ('owner', models.CharField(blank=True, max_length=150, null=True, validators=[rackcity.models.asset.validate_owner])),
                ('comment', models.TextField(blank=True, null=True)),
                ('change_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.ChangePlan')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.ITModel', verbose_name='related model')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.Rack', verbose_name='related rack')),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackcity.Asset')),
            ],
            options={
                'verbose_name': 'asset',
                'ordering': ['asset_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='changeplan',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique change planner name'),
        ),
    ]
