# Generated by Django 3.0.2 on 2020-03-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0020_auto_20200309_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcp',
            options={'ordering': ['asset_number'], 'verbose_name': 'asset change planner'},
        ),
    ]
