# Generated by Django 3.0.2 on 2020-03-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0021_auto_20200309_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assetcp',
            name='id',
        ),
        migrations.AddField(
            model_name='asset',
            name='abstractasset_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rackcity.AbstractAsset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcp',
            name='abstractasset_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rackcity.AbstractAsset'),
            preserve_default=False,
        ),
    ]
