# Generated by Django 3.0.2 on 2020-03-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0022_auto_20200309_2153'),
        ('rackcity', '0022_auto_20200309_1832'),
    ]

    operations = [
    ]
