# Generated by Django 3.0.2 on 2020-03-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0023_auto_20200323_2357'),
        ('rackcity', '0022_auto_20200309_1832'),
    ]

    operations = [
    ]
