# Generated by Django 3.0.2 on 2020-03-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0024_merge_20200324_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbstractAsset',
            new_name='AbstractID',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='abstractasset_ptr',
            new_name='abstractid_ptr',
        ),
        migrations.RenameField(
            model_name='assetcp',
            old_name='abstractasset_ptr',
            new_name='abstractid_ptr',
        ),
    ]
