# Generated by Django 3.0.2 on 2020-03-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0026_auto_20200324_1845'),
        ('rackcity', '0024_auto_20200324_0119'),
    ]

    operations = [
    ]
