# Generated by Django 3.0.2 on 2020-03-25 20:01

from django.db import migrations, models
import django.db.models.deletion
import rackcity.models.asset


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0027_merge_20200324_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcp',
            name='is_decommissioned',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='related_decomissioned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackcity.DecommissionedAsset'),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='hostname',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[rackcity.models.asset.validate_hostname, rackcity.models.asset.validate_hostname_uniqueness]),
        ),
    ]
