# Generated by Django 3.0.2 on 2020-03-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0028_auto_20200325_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcp',
            name='hostname',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
