# Generated by Django 3.0.2 on 2020-03-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0029_auto_20200325_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcp',
            options={'ordering': ['asset_number'], 'verbose_name': 'Asset on Change Plan'},
        ),
    ]
