# Generated by Django 3.0.2 on 2020-03-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0031_auto_20200325_2052'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetcp',
            constraint=models.UniqueConstraint(fields=('hostname', 'change_plan'), name='unique hostnames in a change plan'),
        ),
    ]
