# Generated by Django 3.0.2 on 2020-03-26 21:46

import django.core.validators
from django.db import migrations, models
import rackcity.models.asset


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0032_auto_20200326_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcp',
            name='asset_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='hostname',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[rackcity.models.asset.validate_hostname]),
        ),
    ]
