# Generated by Django 3.0.2 on 2020-03-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0025_auto_20200324_1752'),
        ('rackcity', '0033_auto_20200326_2146'),
    ]

    operations = [
    ]
