# Generated by Django 3.0.2 on 2020-03-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0034_merge_20200327_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcp',
            old_name='related_decomissioned_asset',
            new_name='related_decommissioned_asset',
        ),
    ]
