# Generated by Django 3.0.2 on 2020-03-28 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0036_auto_20200328_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcp',
            name='related_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackcity.Asset'),
        ),
    ]
