# Generated by Django 3.0.2 on 2020-03-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0037_auto_20200328_0206'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetcp',
            name='unique hostnames in a change plan',
        ),
        migrations.AddConstraint(
            model_name='assetcp',
            constraint=models.UniqueConstraint(fields=('hostname', 'change_plan', 'is_decommissioned'), name='unique hostnames in a change plan'),
        ),
    ]
