# Generated by Django 3.0.2 on 2020-03-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0038_auto_20200328_1700'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetcp',
            name='unique hostnames in a change plan',
        ),
    ]
