# Generated by Django 3.0.3 on 2020-04-08 00:21

from django.db import migrations, models
import rackcity.models.it_model


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0040_auto_20200329_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='itmodel',
            name='model_type',
            field=models.CharField(choices=[(rackcity.models.it_model.ModelType['RACKMOUNT_ASSET'], rackcity.models.it_model.ModelType['RACKMOUNT_ASSET']), (rackcity.models.it_model.ModelType['BLADE_CHASSIS'], rackcity.models.it_model.ModelType['BLADE_CHASSIS']), (rackcity.models.it_model.ModelType['BLADE_ASSET'], rackcity.models.it_model.ModelType['BLADE_ASSET'])], default='RACKMOUNT_ASSET', max_length=150),
            preserve_default=False,
        ),
    ]
