# Generated by Django 3.0.3 on 2020-04-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0042_auto_20200407_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='model_type',
            field=models.CharField(choices=[('RACKMOUNT_ASSET', 'RACKMOUNT_ASSET'), ('BLADE_CHASSIS', 'BLADE_CHASSIS'), ('BLADE_ASSET', 'BLADE_ASSET')], max_length=150),
        ),
    ]
