# Generated by Django 3.0.3 on 2020-04-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0043_auto_20200407_2014'),
        ('rackcity', '0043_auto_20200407_2119'),
    ]

    operations = [
    ]
