# Generated by Django 3.0.3 on 2020-04-08 03:01

from django.db import migrations, models
import django.db.models.deletion
import rackcity.models.fields.rackcity_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0044_merge_20200407_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='chassis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rackcity.Asset', verbose_name='blade chassis'),
        ),
        migrations.AddField(
            model_name='asset',
            name='chassis_slot',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='chassis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rackcity.AssetCP', verbose_name='blade chassis'),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='chassis_slot',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rackcity.Rack', verbose_name='related rack'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rack_position',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackcity.Rack', verbose_name='related rack'),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='rack_position',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
    ]
