# Generated by Django 3.0.3 on 2020-04-08 23:53

from django.db import migrations, models
import django.db.models.deletion
import rackcity.models.fields.rackcity_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0045_auto_20200407_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_storage', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='rackcitypermission',
            name='datacenter_permissions',
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='height',
            field=rackcity.models.fields.rackcity_model_fields.RCPositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='offline_storage_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rackcity.Site', verbose_name='offline storage site'),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='offline_storage_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rackcity.Site', verbose_name='offline storage site'),
        ),
        migrations.AddField(
            model_name='rackcitypermission',
            name='site_permissions',
            field=models.ManyToManyField(to='rackcity.Site'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='datacenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackcity.Site', verbose_name='datacenter'),
        ),
        migrations.DeleteModel(
            name='Datacenter',
        ),
    ]
