# Generated by Django 3.0.3 on 2020-04-09 18:45

from django.db import migrations, models
import rackcity.models.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0046_auto_20200408_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='display_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[rackcity.models.model_utils.validate_display_color]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='cpu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='display_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[rackcity.models.model_utils.validate_display_color]),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='storage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='model_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Blade Chassis', 'Blade Chassis'), ('Blade Server ', 'Blade Server ')], max_length=150),
        ),
    ]
