# Generated by Django 3.0.3 on 2020-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0046_auto_20200408_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='model_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Blade Chassis', 'Blade Chassis'), ('Blade Server ', 'Blade Server ')], max_length=150),
        ),
    ]
