# Generated by Django 3.0.3 on 2020-04-09 19:35

from django.db import migrations, models
import rackcity.models.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0047_auto_20200409_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='display_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[rackcity.models.model_utils.validate_display_color]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='display_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[rackcity.models.model_utils.validate_display_color]),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
