# Generated by Django 3.0.3 on 2020-04-11 05:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0047_auto_20200409_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decommissionedasset',
            name='rack',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decommissionedasset',
            name='rack_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
