# Generated by Django 3.0.3 on 2020-04-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0048_auto_20200411_0253'),
        ('rackcity', '0049_auto_20200411_0153'),
    ]

    operations = [
    ]
