# Generated by Django 3.0.3 on 2020-04-15 06:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0050_merge_20200415_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='decommissionedasset',
            name='datacenter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decommissionedasset',
            name='offline_storage_site',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
