# Generated by Django 3.0.3 on 2020-04-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0051_auto_20200415_0253'),
        ('rackcity', '0050_merge_20200413_1600'),
    ]

    operations = [
    ]
