# Generated by Django 3.0.3 on 2020-04-17 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0052_merge_20200416_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcp',
            name='differs_from_live',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='chassis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rackcity.AssetCP', verbose_name='blade chassis'),
        ),
    ]
