# Generated by Django 3.0.3 on 2020-04-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0052_merge_20200416_1547'),
        ('rackcity', '0053_auto_20200416_2333'),
    ]

    operations = [
    ]
