# Generated by Django 3.0.3 on 2020-04-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0054_merge_20200418_0122'),
        ('rackcity', '0054_merge_20200417_2324'),
    ]

    operations = [
    ]
