# Generated by Django 3.0.3 on 2020-04-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0055_auto_20200418_1159'),
        ('rackcity', '0055_merge_20200418_2219'),
    ]

    operations = [
    ]
