# Generated by Django 3.0.3 on 2020-04-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0056_merge_20200419_1322'),
        ('rackcity', '0056_decommissionedasset_blades'),
    ]

    operations = [
    ]
