# Generated by Django 3.0.3 on 2020-04-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackcity', '0057_merge_20200419_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkport',
            name='connected_port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackcity.NetworkPort'),
        ),
        migrations.AlterField(
            model_name='networkportcp',
            name='connected_port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackcity.NetworkPortCP'),
        ),
    ]
